/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright":              "#2A2A2A",
        "tertiary-container":          "#7A5C00",
        "secondary-fixed":             "#F0C040",
        "background":                  "#080808",
        "tertiary-fixed":              "#FFD700",
        "error":                       "#ffb4ab",
        "outline":                     "#666666",
        "inverse-primary":             "#9B7B0E",
        "on-tertiary-fixed-variant":   "#3D2E00",
        "surface-dim":                 "#080808",
        "inverse-on-surface":          "#1A1A1A",
        "tertiary":                    "#D4AF37",
        "error-container":             "#93000a",
        "primary-fixed-dim":           "#C9A227",
        "primary-fixed":               "#F0C040",
        "surface-tint":                "#D4AF37",
        "on-secondary-fixed":          "#0A0800",
        "secondary-container":         "#2D2200",
        "inverse-surface":             "#E8E0CC",
        "primary":                     "#D4AF37",
        "surface-variant":             "#1E1E1E",
        "on-tertiary-fixed":           "#0A0600",
        "secondary":                   "#D4AF37",
        "surface-container-low":       "#101010",
        "on-tertiary":                 "#0A0600",
        "outline-variant":             "#2A2A2A",
        "on-surface-variant":          "#B0A070",
        "on-tertiary-container":       "#1A1000",
        "on-error":                    "#690005",
        "on-secondary-container":      "#F0C040",
        "on-secondary":                "#0A0600",
        "surface-container-lowest":    "#050505",
        "on-error-container":          "#ffdad6",
        "on-surface":                  "#F0E8CC",
        "on-secondary-fixed-variant":  "#3D2E00",
        "on-background":               "#F0E8CC",
        "on-primary-container":        "#1A0D00",
        "primary-container":           "#9B7B0E",
        "surface-container-high":      "#181818",
        "surface":                     "#080808",
        "on-primary-fixed":            "#0A0600",
        "tertiary-fixed-dim":          "#D4AF37",
        "surface-container":           "#141414",
        "on-primary":                  "#080808",
        "surface-container-highest":   "#222222",
        "secondary-fixed-dim":         "#D4AF37",
        "on-primary-fixed-variant":    "#3D2E00",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg":      "0.25rem",
        "xl":      "0.5rem",
        "full":    "9999px",
      },
      fontFamily: {
        "headline": ["Sora", "Space Grotesk", "sans-serif"],
        "body":     ["Inter", "sans-serif"],
        "label":    ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
